<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  
  <ItemGroup>
    <None Remove="Assets\Fonts\SourceHanSansSC.ttf" />
    <None Remove="Assets\Images\closs.png" />
    <None Remove="Assets\Images\closs2.png" />
    <None Remove="Assets\Images\open.png" />
    <None Remove="Assets\Images\open2.png" />
    <None Remove="Assets\Images\Read.png" />
    <None Remove="Assets\Images\set2.png" />
    <None Remove="Assets\Images\signar.png" />
    <None Remove="Assets\Images\systemSet.png" />
    <None Remove="Assets\Images\UnRead.png" />
    <None Remove="Assets\Images\waring.png" />
    <None Remove="Assets\Images\waring2.png" />
    <None Remove="Assets\Images\wukonglogo.png" />
  </ItemGroup>

  
  <ItemGroup>
    <ApplicationDefinition Include="Assets\Fonts\SourceHanSansSC.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.5" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.5" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.5" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.5" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Component\VPortNumberKeyboard.axaml.cs">
      <DependentUpon>VPortNumberKeyboard.axaml</DependentUpon>
    </Compile>
    <Compile Update="Component\VPortCharacterKeyboard.axaml.cs">
      <DependentUpon>VPortCharacterKeyboard.axaml</DependentUpon>
    </Compile>
    <Compile Update="Component\NumberKeyboard.axaml.cs">
      <DependentUpon>NumberKeyboard.axaml</DependentUpon>
    </Compile>
    <Compile Update="Component\SwitchButton.axaml.cs">
      <DependentUpon>SwitchButton.axaml</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VPortSetSerialView.axaml.cs">
      <DependentUpon>VPortSetSerialView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VPortSetNetView.axaml.cs">
      <DependentUpon>VPortSetNetView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VPortSetProtoView.axaml.cs">
      <DependentUpon>VPortSetProtoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VPortSetRuleParamView.axaml.cs">
      <DependentUpon>VPortSetRuleParamView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VPortSetRuleView.axaml.cs">
      <DependentUpon>VPortSetRuleView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
