<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.3" />
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="System.Device.Gpio" Version="3.2.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Third\FastTunnel.Core.Client\FastTunnel.Core.Client.csproj" />
    <ProjectReference Include="..\ChannelUtility\ChannelUtility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
