<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\</OutputPath>
		<DocumentationFile>..\..\App\XML\EfficiencyService.xml</DocumentationFile>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\..\TemplateAction.NetCore\TemplateAction.NetCore.csproj" />
    <ProjectReference Include="..\..\TemplateAction\TemplateAction.csproj" />
    <ProjectReference Include="..\AfterService\AfterService.csproj" />
    <ProjectReference Include="..\AuthService\AuthService.csproj" />
  </ItemGroup>

</Project>
