<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\</OutputPath>
		<DocumentationFile>..\..\App\XML\CardService.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeveloperService\DeveloperService.csproj" />
		<ProjectReference Include="..\MonitorService\MonitorService.csproj" />
		<ProjectReference Include="..\WeiXinService\WeiXinService.csproj" />
	</ItemGroup>
</Project>
