<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Description>This is an ORM processing framework，The source address：https://gitee.com/mz-cn/MZFrame.
HOW TO USE： new SqlBuilder(new MySqlHelp("conn")).AppendInsert(model, "table").Do&lt;DoExecSql&gt;().RowCount;</Description>
    <Authors>重新读取</Authors>
    <Version>5.0.1</Version>
    <Copyright>Copyright © 重新读取 2021</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspectCore.Core" Version="2.4.0" />
  </ItemGroup>

</Project>
