<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net9.0;netstandard2.1;</TargetFrameworks>
    <Description>This is an ORM processing framework，The source address：https://gitee.com/reread_x/openaiot
The MyAccess has been split into MyAccess、MyAccess.MSSql、MyAccess.MySql、MyAccess.Oracle、MyAccess.Sqlite， When using a MySQL database, simply reference MyAccess and MyAccess. MySQL.</Description>
    <Authors>重新读取</Authors>
    <Version>5.0.5</Version>
    <Copyright>Copyright © 重新读取 2021</Copyright>
    <PackageReadmeFile>MyAccess 完整使用手册.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/wrq147/OpenAIot</PackageProjectUrl>
	<LangVersion>10.0</LangVersion>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\MyAccess 完整使用手册.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspectCore.Core" Version="2.4.0" />
  </ItemGroup>

</Project>
