/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.6-11-gcde3c5fc0c-20241231"
#endif /* AVUTIL_FFVERSION_H */
