<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\</OutputPath>
		<DocumentationFile>..\..\App\XML\MESService.xml</DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\AuthService\AuthService.csproj" />
	  <ProjectReference Include="..\FlowService\FlowService.csproj" />
	  <ProjectReference Include="..\ProducerService\ProducerService.csproj" />
	</ItemGroup>

</Project>
