<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\</OutputPath>
		<DocumentationFile>..\..\App\XML\IoTRulesService.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AuthService\AuthService.csproj" />
		<ProjectReference Include="..\DeveloperService\DeveloperService.csproj" />
		<ProjectReference Include="..\IoTService\IoTService.csproj" />
		<ProjectReference Include="..\MonitorService\MonitorService.csproj" />
	</ItemGroup>
</Project>
