<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType> 
		<TargetFramework>net7.0</TargetFramework>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Common\Common.csproj" />
		<ProjectReference Include="..\Modules\AfterService\AfterService.csproj" />
		<ProjectReference Include="..\Modules\AuthService\AuthService.csproj" />
		<ProjectReference Include="..\Modules\CRMService\CRMService.csproj" />
		<ProjectReference Include="..\Modules\DeveloperService\DeveloperService.csproj" />
		<ProjectReference Include="..\Modules\DictService\DictService.csproj" />
		<ProjectReference Include="..\Modules\DiscussService\DiscussService.csproj" />
		<ProjectReference Include="..\Modules\EmailService\EmailService.csproj" />
		<ProjectReference Include="..\Modules\FlowService\FlowService.csproj" />
		<ProjectReference Include="..\Modules\IoTAIService\IoTAIService.csproj" />
		<ProjectReference Include="..\Modules\IoTRulesService\IoTRulesService.csproj" />
		<ProjectReference Include="..\Modules\IoTService\IoTService.csproj" />
		<ProjectReference Include="..\Modules\IoTVideoService\IoTVideoService.csproj" />
		<ProjectReference Include="..\Modules\MessageService\MessageService.csproj" />
		<ProjectReference Include="..\Modules\MESService\MESService.csproj" />
		<ProjectReference Include="..\Modules\MonitorService\MonitorService.csproj" />
		<ProjectReference Include="..\Modules\MqttService\MqttService.csproj" />
		<ProjectReference Include="..\Modules\PayService\PayService.csproj" />
		<ProjectReference Include="..\Modules\ProducerService\ProducerService.csproj" />
		<ProjectReference Include="..\Modules\ReportService\ReportService.csproj" />
		<ProjectReference Include="..\Modules\SaleService\SaleService.csproj" />
		<ProjectReference Include="..\Modules\ShortLinkService\ShortLinkService.csproj" />
		<ProjectReference Include="..\Modules\SMSService\SMSService.csproj" />
		<ProjectReference Include="..\Modules\StorageService\StorageService.csproj" />
		<ProjectReference Include="..\Modules\ThirdPartyService\ThirdPartyService.csproj" />
		<ProjectReference Include="..\Modules\WeiXinService\WeiXinService.csproj" />
		<ProjectReference Include="..\MyAccess\MyAccess.csproj" />
		<ProjectReference Include="..\TemplateAction.NetCore\TemplateAction.NetCore.csproj" />
		<ProjectReference Include="..\TemplateAction\TemplateAction.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\company.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\danniao.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\debangkuaidi.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\debangwuliu.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\huitongkuaidi.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\jtexpress.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\shentong.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\shunfeng.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\tiantian.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\yuantong.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\yunda.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\zhongtong.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\zhongtongguoji.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="data_set\zhongtongkuaiyun.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\char_state_tab.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\cn_synonym.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\dict.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\idf.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\pos_prob_emit.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\pos_prob_start.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\pos_prob_trans.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\prob_emit.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\prob_trans.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Jieba\stopwords.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="log4net.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="qqwry.dat">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="services.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\1.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\10.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\11.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\12.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\13.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\14.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\15.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\16.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\2.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\3.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\4.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\5.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\6.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\7.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\8.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\bg\9.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\yx\1.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\yx\2.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\yx\3.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\yx\4.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="www\yx\5.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\AgentService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\AuthService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\CardService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\ChannelUtility.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\Common.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\CRMService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\DeveloperService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\DictService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\DiscussService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\EmailService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\FlowService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\IoTRulesService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\IoTService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\MessageService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\MonitorService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\MqttService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\ReportService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\SMSService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="XML\WeiXinService.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="www\bg\" />
	  <Folder Include="Jieba\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="6.1.0" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.2" />
	</ItemGroup>

</Project>
