//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TemplateAction.Label.Token
{
    public abstract class BaseToken
    {
        protected string mValue;
        protected string mToken;
        /// <summary>
        /// 标记种类，一般是首字符，结构体则为value值
        /// </summary>
        public string Token
        {
            get { return mToken; }
        }
        public int Length
        {
            get
            {
                return mValue.Length;
            }
        }
        public override string ToString()
        {
            if (mValue != null)
            {
                return mValue;
            }
            else
            {
                return string.Empty;
            }
        }
        public BaseToken(string token)
        {
            mValue = token;
            mToken = token;
        }
        public T Value<T>()
        {
            object val = GetValue();
            // 处理空值（如果 T 是可空类型，直接返回 null）
            if (val == null)
            {
                // 若 T 为非可空值类型，会在 (T)val 处抛异常，符合 Convert 类的默认行为
                return (T)val;
            }
            Type targetType = typeof(T);
            Type sourceType = val.GetType();
            // 如果源类型可直接转换为目标类型，无需额外处理
            if (targetType.IsAssignableFrom(sourceType))
            {
                return (T)val;
            }
            if (Common.TAUtility.IsNumerical(targetType))
            {
                try
                {
                    val = Convert.ChangeType(val, targetType);
                }
                catch (InvalidCastException ex)
                {
                    // 处理转换失败的情况（如数值超出目标类型范围）
                    throw new InvalidOperationException($"无法将 {val} 从 {sourceType} 转换为 {targetType}", ex);
                }
            }
            return (T)val;
        }
        public abstract object GetValue();
        public abstract bool Append(char value);
        public abstract string Type { get; }
    }
}

