//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace TemplateAction.Label.Token
{
    /// <summary>
    /// 字符串标记
    /// </summary>
    public class StringToken : BaseToken
    {
        public const char DOUBLE_QUOTES = '\"';
        public const char SINGLE_QUOTES = '\'';
        protected StringBuilder _str = new StringBuilder();
        protected bool _islastEscape;
        public const string TOKEN_TYPE = "String";
        public override object GetValue()
        {
            return _str.ToString();
        }
        public StringToken(string val)
            : base(val)
        {
            _islastEscape = false;
        }

        public override bool Append(char value)
        {
            mValue += value;
            if (_islastEscape)
            {
                if (_str.Length > 0)
                {
                    _str[_str.Length - 1] = value;
                }
                _islastEscape = false;
                return true;
            }
            else
            {
                if (value != mToken[0])
                {
                    if (value == '\\')
                    {
                        _islastEscape = true;
                    }
                    _str.Append(value);
                    return true;
                }
            }
            return false;
        }
        public override string Type
        {
            get { return TOKEN_TYPE; }
        }
    }
}

