//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TemplateAction.Label.Token
{
    /// <summary>
    /// 未定义标记
    /// </summary>
    public class UndefinedToken : BaseToken
    {
        public const string TOKEN_TYPE = "Undefined";
        public UndefinedToken(string val) : base(val) { }
        public override object GetValue()
        {
            return mValue;
        }
        public override bool Append(char value)
        {
            return false;
        }

        public override string Type
        {
            get { return TOKEN_TYPE; }
        }
    }

}