// 连接配置参数
export type ConnectorOptions = {
	address : string,
	port : number,
	success ?: () => void
	fail ?: (res : any) => void
	onMessage ?: (data : string) => void
	onClose ?: () => void
}

// TCP错误码定义
export type ConnectorErrorCode = 902001 | 902002 | 902003;

// 错误对象规范接口
export interface ConnectorFail extends IUniError {
	errCode: ConnectorErrorCode
}

// 创建TCP工厂函数类型，返回连接ID
export type TcpConnector = (options: ConnectorOptions) => number;

// 写入二进制数据（data 为 base64 编码字符串）
export type TcpWriter = (id: number, data: string) => void;
