// 连接配置参数
export type ConnectorOptions = {
	address : string,
	port : number,
	success ?: (res : ITcpConnector) => void
	fail ?: (res : any) => void
}

// TCP错误码定义
export type ConnectorErrorCode = 902001 | 902002 | 902003;

// 错误对象规范接口
export interface ConnectorFail extends IUniError {
	errCode: ConnectorErrorCode
}

// TCP客户端对外标准接口
export interface ITcpConnector {
	onClose: (() => void) | null;
	onMessage: ((data: ArrayBuffer) => void) | null;
	close(): void;
	write(data: ArrayBuffer): void;
	writeString(data: string): void;
}

// 创建TCP工厂函数类型
export type TcpConnector = (options: ConnectorOptions) => ITcpConnector