import { ConnectorErrorCode, ConnectorFail } from "./interface.uts"

export const UniErrorSubject = 'qzadsl-tcp';

export const ConnectorErrors : Map<ConnectorErrorCode, string> = new Map([
	[902001, "TCP连接失败"],
	[902002, "数据写入异常"],
	[902003, "流读取中断"],
]);

export class ConnectorFailImpl extends UniError implements ConnectorFail {
	override errCode: ConnectorErrorCode
	constructor(errCode : ConnectorErrorCode, msg?: string) {
		super();
		this.errSubject = UniErrorSubject;
		this.errCode = errCode;
		this.errMsg = msg ?? ConnectorErrors.get(err) ?? "";
	}
}