<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	 <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
	<PackageReference Include="Jint" Version="3.1.0" />
	<PackageReference Include="MessagePack" Version="3.1.4" />
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
	  <PackageReference Include="NATS.Client.Core" Version="2.7.1" />
	  <PackageReference Include="NetMQ" Version="4.0.2.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
  </ItemGroup>

</Project>
