//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirJointUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirJointUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 485压力传感器 的本地化字符串。
        /// </summary>
        internal static string _485压力传感器 {
            get {
                return ResourceManager.GetString("485压力传感器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警描述： 的本地化字符串。
        /// </summary>
        internal static string AlarmDes {
            get {
                return ResourceManager.GetString("AlarmDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警设备： 的本地化字符串。
        /// </summary>
        internal static string AlarmDevice {
            get {
                return ResourceManager.GetString("AlarmDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警名称： 的本地化字符串。
        /// </summary>
        internal static string AlarmName {
            get {
                return ResourceManager.GetString("AlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警时间： 的本地化字符串。
        /// </summary>
        internal static string AlarmTime {
            get {
                return ResourceManager.GetString("AlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警列表 的本地化字符串。
        /// </summary>
        internal static string AlarmTitle {
            get {
                return ResourceManager.GetString("AlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确定要恢复设备状态？ 的本地化字符串。
        /// </summary>
        internal static string AllRestoreTip {
            get {
                return ResourceManager.GetString("AllRestoreTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确定要保存所有设备状态并关闭？ 的本地化字符串。
        /// </summary>
        internal static string AllStopTip {
            get {
                return ResourceManager.GetString("AllStopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用 的本地化字符串。
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大写 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardCaps {
            get {
                return ResourceManager.GetString("CharacterKeyboardCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardClose {
            get {
                return ResourceManager.GetString("CharacterKeyboardClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardDel {
            get {
                return ResourceManager.GetString("CharacterKeyboardDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请通过按键输入内容 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardInputTip {
            get {
                return ResourceManager.GetString("CharacterKeyboardInputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小写 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardNormal {
            get {
                return ResourceManager.GetString("CharacterKeyboardNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardOk {
            get {
                return ResourceManager.GetString("CharacterKeyboardOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空格 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardSpace {
            get {
                return ResourceManager.GetString("CharacterKeyboardSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符键盘 的本地化字符串。
        /// </summary>
        internal static string CharacterKeyboardTitle {
            get {
                return ResourceManager.GetString("CharacterKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部处理 的本地化字符串。
        /// </summary>
        internal static string ClearUp {
            get {
                return ResourceManager.GetString("ClearUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置异常: 的本地化字符串。
        /// </summary>
        internal static string ConfigurationException {
            get {
                return ResourceManager.GetString("ConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置失败 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFailed {
            get {
                return ResourceManager.GetString("ConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认消息 的本地化字符串。
        /// </summary>
        internal static string ConfirmBoxTitle {
            get {
                return ResourceManager.GetString("ConfirmBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备配置 的本地化字符串。
        /// </summary>
        internal static string DeviceSetTag {
            get {
                return ResourceManager.GetString("DeviceSetTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备({0}) 的本地化字符串。
        /// </summary>
        internal static string DeviceTag {
            get {
                return ResourceManager.GetString("DeviceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ip与端口 的本地化字符串。
        /// </summary>
        internal static string DevNetIpPort {
            get {
                return ResourceManager.GetString("DevNetIpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备通信方式 的本地化字符串。
        /// </summary>
        internal static string DevNetWayTip {
            get {
                return ResourceManager.GetString("DevNetWayTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string DisplayStatus {
            get {
                return ResourceManager.GetString("DisplayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍等... 的本地化字符串。
        /// </summary>
        internal static string Doing {
            get {
                return ResourceManager.GetString("Doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报文间隔[毫秒] 的本地化字符串。
        /// </summary>
        internal static string DownInterval {
            get {
                return ResourceManager.GetString("DownInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机电流(A) 的本地化字符串。
        /// </summary>
        internal static string EngineCurrent {
            get {
                return ResourceManager.GetString("EngineCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机输出频率(Hz) 的本地化字符串。
        /// </summary>
        internal static string EngineFrequency {
            get {
                return ResourceManager.GetString("EngineFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机功率 的本地化字符串。
        /// </summary>
        internal static string EnginePower {
            get {
                return ResourceManager.GetString("EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行失败 的本地化字符串。
        /// </summary>
        internal static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行成功 的本地化字符串。
        /// </summary>
        internal static string ExecutionSuccessful {
            get {
                return ResourceManager.GetString("ExecutionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排气温度 的本地化字符串。
        /// </summary>
        internal static string ExhaustTemperature {
            get {
                return ResourceManager.GetString("ExhaustTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 横向 的本地化字符串。
        /// </summary>
        internal static string HorizDir {
            get {
                return ResourceManager.GetString("HorizDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明信息 的本地化字符串。
        /// </summary>
        internal static string InfoBoxTitle {
            get {
                return ResourceManager.GetString("InfoBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前IP：{0} 的本地化字符串。
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联控状态 的本地化字符串。
        /// </summary>
        internal static string JointControlStatus {
            get {
                return ResourceManager.GetString("JointControlStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联控系统初始化中{0} 的本地化字符串。
        /// </summary>
        internal static string LoadingTxt {
            get {
                return ResourceManager.GetString("LoadingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空压机联控系统 的本地化字符串。
        /// </summary>
        internal static string LogoTxt {
            get {
                return ResourceManager.GetString("LogoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lora管道压力联控 的本地化字符串。
        /// </summary>
        internal static string lora管道压力联控 {
            get {
                return ResourceManager.GetString("lora管道压力联控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lora设备上线规则 的本地化字符串。
        /// </summary>
        internal static string lora设备上线规则 {
            get {
                return ResourceManager.GetString("lora设备上线规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lora设备属性上报规则 的本地化字符串。
        /// </summary>
        internal static string lora设备属性上报规则 {
            get {
                return ResourceManager.GetString("lora设备属性上报规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lora设备离线规则 的本地化字符串。
        /// </summary>
        internal static string lora设备离线规则 {
            get {
                return ResourceManager.GetString("lora设备离线规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lora通信 的本地化字符串。
        /// </summary>
        internal static string Lora通信 {
            get {
                return ResourceManager.GetString("Lora通信", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示消息 的本地化字符串。
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多参数 的本地化字符串。
        /// </summary>
        internal static string MoreTxt {
            get {
                return ResourceManager.GetString("MoreTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动选择 的本地化字符串。
        /// </summary>
        internal static string NetCombo0 {
            get {
                return ResourceManager.GetString("NetCombo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口通信 的本地化字符串。
        /// </summary>
        internal static string NetCombo1 {
            get {
                return ResourceManager.GetString("NetCombo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网口通信 的本地化字符串。
        /// </summary>
        internal static string NetCombo2 {
            get {
                return ResourceManager.GetString("NetCombo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络设置 的本地化字符串。
        /// </summary>
        internal static string NetSetTag {
            get {
                return ResourceManager.GetString("NetSetTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string nextPage {
            get {
                return ResourceManager.GetString("nextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清零 的本地化字符串。
        /// </summary>
        internal static string NumberKeyboardClear {
            get {
                return ResourceManager.GetString("NumberKeyboardClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string NumberKeyboardClose {
            get {
                return ResourceManager.GetString("NumberKeyboardClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string NumberKeyboardConfirm {
            get {
                return ResourceManager.GetString("NumberKeyboardConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string NumberKeyboardDel {
            get {
                return ResourceManager.GetString("NumberKeyboardDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字键盘 的本地化字符串。
        /// </summary>
        internal static string NumberKeyboardTitle {
            get {
                return ResourceManager.GetString("NumberKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备已离线，无法显示实时数据 的本地化字符串。
        /// </summary>
        internal static string OffData {
            get {
                return ResourceManager.GetString("OffData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行成功 的本地化字符串。
        /// </summary>
        internal static string OpSuccess {
            get {
                return ResourceManager.GetString("OpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 页 / 共 {1} 页 的本地化字符串。
        /// </summary>
        internal static string PageTJ {
            get {
                return ResourceManager.GetString("PageTJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置参数 的本地化字符串。
        /// </summary>
        internal static string ParamButton {
            get {
                return ResourceManager.GetString("ParamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纵向 的本地化字符串。
        /// </summary>
        internal static string PortraitDir {
            get {
                return ResourceManager.GetString("PortraitDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string prevPage {
            get {
                return ResourceManager.GetString("prevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议 的本地化字符串。
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划停机 的本地化字符串。
        /// </summary>
        internal static string ReadyHalt {
            get {
                return ResourceManager.GetString("ReadyHalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划运行 的本地化字符串。
        /// </summary>
        internal static string ReadyRun {
            get {
                return ResourceManager.GetString("ReadyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启系统 的本地化字符串。
        /// </summary>
        internal static string RebootButton {
            get {
                return ResourceManager.GetString("RebootButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确定重启系统？ 的本地化字符串。
        /// </summary>
        internal static string RebootTip {
            get {
                return ResourceManager.GetString("RebootTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参考值 的本地化字符串。
        /// </summary>
        internal static string ReferenceValue {
            get {
                return ResourceManager.GetString("ReferenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远控代码：{0} 的本地化字符串。
        /// </summary>
        internal static string RemoteCode {
            get {
                return ResourceManager.GetString("RemoteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已解决 的本地化字符串。
        /// </summary>
        internal static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复联控 的本地化字符串。
        /// </summary>
        internal static string RestoreState {
            get {
                return ResourceManager.GetString("RestoreState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RS232传感器 的本地化字符串。
        /// </summary>
        internal static string RS232传感器 {
            get {
                return ResourceManager.GetString("RS232传感器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RS485传感器 的本地化字符串。
        /// </summary>
        internal static string RS485传感器 {
            get {
                return ResourceManager.GetString("RS485传感器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联控规则 的本地化字符串。
        /// </summary>
        internal static string RuleSetTag {
            get {
                return ResourceManager.GetString("RuleSetTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间(小时) 的本地化字符串。
        /// </summary>
        internal static string RunTimes {
            get {
                return ResourceManager.GetString("RunTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置保存后需要重启，是否确定？ 的本地化字符串。
        /// </summary>
        internal static string SaveTip {
            get {
                return ResourceManager.GetString("SaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕方向 的本地化字符串。
        /// </summary>
        internal static string ScreenOri {
            get {
                return ResourceManager.GetString("ScreenOri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮询间隔[毫秒] 的本地化字符串。
        /// </summary>
        internal static string SendInterval {
            get {
                return ResourceManager.GetString("SendInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器({0}) 的本地化字符串。
        /// </summary>
        internal static string SensorTag {
            get {
                return ResourceManager.GetString("SensorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用配置 的本地化字符串。
        /// </summary>
        internal static string SerialSet {
            get {
                return ResourceManager.GetString("SerialSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关停 的本地化字符串。
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭联控 的本地化字符串。
        /// </summary>
        internal static string ShutdownAll {
            get {
                return ResourceManager.GetString("ShutdownAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止异常: 的本地化字符串。
        /// </summary>
        internal static string ShutdownException {
            get {
                return ResourceManager.GetString("ShutdownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止失败 的本地化字符串。
        /// </summary>
        internal static string ShutdownFailed {
            get {
                return ResourceManager.GetString("ShutdownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WIFI名称 的本地化字符串。
        /// </summary>
        internal static string SSID {
            get {
                return ResourceManager.GetString("SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入WIFI名称 的本地化字符串。
        /// </summary>
        internal static string SSIDPlaceholder {
            get {
                return ResourceManager.GetString("SSIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动异常: 的本地化字符串。
        /// </summary>
        internal static string StartException {
            get {
                return ResourceManager.GetString("StartException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        internal static string StartFailed {
            get {
                return ResourceManager.GetString("StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单状态： 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停机时间(小时) 的本地化字符串。
        /// </summary>
        internal static string StopTimes {
            get {
                return ResourceManager.GetString("StopTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供气压力 的本地化字符串。
        /// </summary>
        internal static string SupplyPressure {
            get {
                return ResourceManager.GetString("SupplyPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时区 的本地化字符串。
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 息屏时间[分钟] 的本地化字符串。
        /// </summary>
        internal static string TurnOffTime {
            get {
                return ResourceManager.GetString("TurnOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UART传感器 的本地化字符串。
        /// </summary>
        internal static string UART传感器 {
            get {
                return ResourceManager.GetString("UART传感器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用中 的本地化字符串。
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警提示 的本地化字符串。
        /// </summary>
        internal static string WarnButton {
            get {
                return ResourceManager.GetString("WarnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计报表 的本地化字符串。
        /// </summary>
        internal static string WebReport {
            get {
                return ResourceManager.GetString("WebReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wifi密码错误 的本地化字符串。
        /// </summary>
        internal static string WifiPasswordError {
            get {
                return ResourceManager.GetString("WifiPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WIFI开关 的本地化字符串。
        /// </summary>
        internal static string WifiSwitch {
            get {
                return ResourceManager.GetString("WifiSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机不平衡 的本地化字符串。
        /// </summary>
        internal static string 主机不平衡 {
            get {
                return ResourceManager.GetString("主机不平衡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机变频器故障 的本地化字符串。
        /// </summary>
        internal static string 主机变频器故障 {
            get {
                return ResourceManager.GetString("主机变频器故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机变频器故障IO 的本地化字符串。
        /// </summary>
        internal static string 主机变频器故障IO {
            get {
                return ResourceManager.GetString("主机变频器故障IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机变频器通讯故障 的本地化字符串。
        /// </summary>
        internal static string 主机变频器通讯故障 {
            get {
                return ResourceManager.GetString("主机变频器通讯故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机缺相 的本地化字符串。
        /// </summary>
        internal static string 主机缺相 {
            get {
                return ResourceManager.GetString("主机缺相", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机过载 的本地化字符串。
        /// </summary>
        internal static string 主机过载 {
            get {
                return ResourceManager.GetString("主机过载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主电机风扇故障 的本地化字符串。
        /// </summary>
        internal static string 主电机风扇故障 {
            get {
                return ResourceManager.GetString("主电机风扇故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用错误 的本地化字符串。
        /// </summary>
        internal static string 使用错误 {
            get {
                return ResourceManager.GetString("使用错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供气压力传感器失灵 的本地化字符串。
        /// </summary>
        internal static string 供气压力传感器失灵 {
            get {
                return ResourceManager.GetString("供气压力传感器失灵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供气压力高 的本地化字符串。
        /// </summary>
        internal static string 供气压力高 {
            get {
                return ResourceManager.GetString("供气压力高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停机 的本地化字符串。
        /// </summary>
        internal static string 停机 {
            get {
                return ResourceManager.GetString("停机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停机延时[秒] 的本地化字符串。
        /// </summary>
        internal static string 停机延时_秒_ {
            get {
                return ResourceManager.GetString("停机延时[秒]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许同时运行的设备数量 的本地化字符串。
        /// </summary>
        internal static string 允许同时运行的设备数量 {
            get {
                return ResourceManager.GetString("允许同时运行的设备数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷却水开关 的本地化字符串。
        /// </summary>
        internal static string 冷却水开关 {
            get {
                return ResourceManager.GetString("冷却水开关", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷干机故障 的本地化字符串。
        /// </summary>
        internal static string 冷干机故障 {
            get {
                return ResourceManager.GetString("冷干机故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前轴承温度传感器失灵 的本地化字符串。
        /// </summary>
        internal static string 前轴承温度传感器失灵 {
            get {
                return ResourceManager.GetString("前轴承温度传感器失灵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前轴承温度高 的本地化字符串。
        /// </summary>
        internal static string 前轴承温度高 {
            get {
                return ResourceManager.GetString("前轴承温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载压力 的本地化字符串。
        /// </summary>
        internal static string 加载压力 {
            get {
                return ResourceManager.GetString("加载压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载压力 的本地化字符串。
        /// </summary>
        internal static string 卸载压力 {
            get {
                return ResourceManager.GetString("卸载压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参考压力的数据来源 的本地化字符串。
        /// </summary>
        internal static string 参考压力的数据来源 {
            get {
                return ResourceManager.GetString("参考压力的数据来源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注说明 的本地化字符串。
        /// </summary>
        internal static string 备注说明 {
            get {
                return ResourceManager.GetString("备注说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多路RS485管道压力联控 的本地化字符串。
        /// </summary>
        internal static string 多路RS485管道压力联控 {
            get {
                return ResourceManager.GetString("多路RS485管道压力联控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已处理 的本地化字符串。
        /// </summary>
        internal static string 已处理 {
            get {
                return ResourceManager.GetString("已处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机延时[秒] 的本地化字符串。
        /// </summary>
        internal static string 开机延时_秒_ {
            get {
                return ResourceManager.GetString("开机延时[秒]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待处理 的本地化字符串。
        /// </summary>
        internal static string 待处理 {
            get {
                return ResourceManager.GetString("待处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线485压力联控 的本地化字符串。
        /// </summary>
        internal static string 总线485压力联控 {
            get {
                return ResourceManager.GetString("总线485压力联控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线485设备上线规则 的本地化字符串。
        /// </summary>
        internal static string 总线485设备上线规则 {
            get {
                return ResourceManager.GetString("总线485设备上线规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线485设备属性上报规则 的本地化字符串。
        /// </summary>
        internal static string 总线485设备属性上报规则 {
            get {
                return ResourceManager.GetString("总线485设备属性上报规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线485设备离线规则 的本地化字符串。
        /// </summary>
        internal static string 总线485设备离线规则 {
            get {
                return ResourceManager.GetString("总线485设备离线规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线通信 的本地化字符串。
        /// </summary>
        internal static string 总线通信 {
            get {
                return ResourceManager.GetString("总线通信", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排气温度传感器失灵 的本地化字符串。
        /// </summary>
        internal static string 排气温度传感器失灵 {
            get {
                return ResourceManager.GetString("排气温度传感器失灵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排气温度高 的本地化字符串。
        /// </summary>
        internal static string 排气温度高 {
            get {
                return ResourceManager.GetString("排气温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排水时间过久 的本地化字符串。
        /// </summary>
        internal static string 排水时间过久 {
            get {
                return ResourceManager.GetString("排水时间过久", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string 无 {
            get {
                return ResourceManager.GetString("无", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普乐特6070 的本地化字符串。
        /// </summary>
        internal static string 普乐特6070 {
            get {
                return ResourceManager.GetString("普乐特6070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6070控制器告警 的本地化字符串。
        /// </summary>
        internal static string 普乐特6070控制器告警 {
            get {
                return ResourceManager.GetString("普乐特6070控制器告警", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多运行数量 的本地化字符串。
        /// </summary>
        internal static string 最多运行数量 {
            get {
                return ResourceManager.GetString("最多运行数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机械油封泄露 的本地化字符串。
        /// </summary>
        internal static string 机械油封泄露 {
            get {
                return ResourceManager.GetString("机械油封泄露", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气罐温度高 的本地化字符串。
        /// </summary>
        internal static string 气罐温度高 {
            get {
                return ResourceManager.GetString("气罐温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水压低 的本地化字符串。
        /// </summary>
        internal static string 水压低 {
            get {
                return ResourceManager.GetString("水压低", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水硬度超标 的本地化字符串。
        /// </summary>
        internal static string 水硬度超标 {
            get {
                return ResourceManager.GetString("水硬度超标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油分器使用时间到 的本地化字符串。
        /// </summary>
        internal static string 油分器使用时间到 {
            get {
                return ResourceManager.GetString("油分器使用时间到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油分器堵塞 的本地化字符串。
        /// </summary>
        internal static string 油分器堵塞 {
            get {
                return ResourceManager.GetString("油分器堵塞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油滤器使用时间到 的本地化字符串。
        /// </summary>
        internal static string 油滤器使用时间到 {
            get {
                return ResourceManager.GetString("油滤器使用时间到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 油滤器堵塞 的本地化字符串。
        /// </summary>
        internal static string 油滤器堵塞 {
            get {
                return ResourceManager.GetString("油滤器堵塞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 润滑油使用时间到 的本地化字符串。
        /// </summary>
        internal static string 润滑油使用时间到 {
            get {
                return ResourceManager.GetString("润滑油使用时间到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 润滑脂使用时间到 的本地化字符串。
        /// </summary>
        internal static string 润滑脂使用时间到 {
            get {
                return ResourceManager.GetString("润滑脂使用时间到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境温度传感器失灵 的本地化字符串。
        /// </summary>
        internal static string 环境温度传感器失灵 {
            get {
                return ResourceManager.GetString("环境温度传感器失灵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境温度高 的本地化字符串。
        /// </summary>
        internal static string 环境温度高 {
            get {
                return ResourceManager.GetString("环境温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压过低 的本地化字符串。
        /// </summary>
        internal static string 电压过低 {
            get {
                return ResourceManager.GetString("电压过低", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压过高 的本地化字符串。
        /// </summary>
        internal static string 电压过高 {
            get {
                return ResourceManager.GetString("电压过高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机温度高 的本地化字符串。
        /// </summary>
        internal static string 电机温度高 {
            get {
                return ResourceManager.GetString("电机温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机过载 的本地化字符串。
        /// </summary>
        internal static string 电机过载 {
            get {
                return ResourceManager.GetString("电机过载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机高温 的本地化字符串。
        /// </summary>
        internal static string 电机高温 {
            get {
                return ResourceManager.GetString("电机高温", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电气故障 的本地化字符串。
        /// </summary>
        internal static string 电气故障 {
            get {
                return ResourceManager.GetString("电气故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相序错误1 的本地化字符串。
        /// </summary>
        internal static string 相序错误1 {
            get {
                return ResourceManager.GetString("相序错误1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相序错误2 的本地化字符串。
        /// </summary>
        internal static string 相序错误2 {
            get {
                return ResourceManager.GetString("相序错误2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定方差 的本地化字符串。
        /// </summary>
        internal static string 稳定方差 {
            get {
                return ResourceManager.GetString("稳定方差", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定记录数 的本地化字符串。
        /// </summary>
        internal static string 稳定记录数 {
            get {
                return ResourceManager.GetString("稳定记录数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空压机控制器告警 的本地化字符串。
        /// </summary>
        internal static string 空压机控制器告警 {
            get {
                return ResourceManager.GetString("空压机控制器告警", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空压机通信协议 的本地化字符串。
        /// </summary>
        internal static string 空压机通信协议 {
            get {
                return ResourceManager.GetString("空压机通信协议", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空压机通信协议650 的本地化字符串。
        /// </summary>
        internal static string 空压机通信协议650 {
            get {
                return ResourceManager.GetString("空压机通信协议650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空滤器使用时间到 的本地化字符串。
        /// </summary>
        internal static string 空滤器使用时间到 {
            get {
                return ResourceManager.GetString("空滤器使用时间到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空滤器堵塞 的本地化字符串。
        /// </summary>
        internal static string 空滤器堵塞 {
            get {
                return ResourceManager.GetString("空滤器堵塞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管道压力 的本地化字符串。
        /// </summary>
        internal static string 管道压力 {
            get {
                return ResourceManager.GetString("管道压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管道压力监测 的本地化字符串。
        /// </summary>
        internal static string 管道压力监测 {
            get {
                return ResourceManager.GetString("管道压力监测", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管道压力离线报警 的本地化字符串。
        /// </summary>
        internal static string 管道压力离线报警 {
            get {
                return ResourceManager.GetString("管道压力离线报警", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统压力传感器失灵 的本地化字符串。
        /// </summary>
        internal static string 系统压力传感器失灵 {
            get {
                return ResourceManager.GetString("系统压力传感器失灵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统压力低 的本地化字符串。
        /// </summary>
        internal static string 系统压力低 {
            get {
                return ResourceManager.GetString("系统压力低", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线圈温度高 的本地化字符串。
        /// </summary>
        internal static string 线圈温度高 {
            get {
                return ResourceManager.GetString("线圈温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺水 的本地化字符串。
        /// </summary>
        internal static string 缺水 {
            get {
                return ResourceManager.GetString("缺水", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联控压力来源 的本地化字符串。
        /// </summary>
        internal static string 联控压力来源 {
            get {
                return ResourceManager.GetString("联控压力来源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水桶缺水 的本地化字符串。
        /// </summary>
        internal static string 补水桶缺水 {
            get {
                return ResourceManager.GetString("补水桶缺水", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1 的本地化字符串。
        /// </summary>
        internal static string 设备1 {
            get {
                return ResourceManager.GetString("设备1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1优先级 的本地化字符串。
        /// </summary>
        internal static string 设备1优先级 {
            get {
                return ResourceManager.GetString("设备1优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备1停机时间 {
            get {
                return ResourceManager.GetString("设备1停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1压力 的本地化字符串。
        /// </summary>
        internal static string 设备1压力 {
            get {
                return ResourceManager.GetString("设备1压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备1启用轮换 {
            get {
                return ResourceManager.GetString("设备1启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备1最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备1最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备1运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备1运行时间 {
            get {
                return ResourceManager.GetString("设备1运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2 的本地化字符串。
        /// </summary>
        internal static string 设备2 {
            get {
                return ResourceManager.GetString("设备2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2优先级 的本地化字符串。
        /// </summary>
        internal static string 设备2优先级 {
            get {
                return ResourceManager.GetString("设备2优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备2停机时间 {
            get {
                return ResourceManager.GetString("设备2停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2压力 的本地化字符串。
        /// </summary>
        internal static string 设备2压力 {
            get {
                return ResourceManager.GetString("设备2压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备2启用轮换 {
            get {
                return ResourceManager.GetString("设备2启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备2最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备2最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备2运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备2运行时间 {
            get {
                return ResourceManager.GetString("设备2运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3 的本地化字符串。
        /// </summary>
        internal static string 设备3 {
            get {
                return ResourceManager.GetString("设备3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3优先级 的本地化字符串。
        /// </summary>
        internal static string 设备3优先级 {
            get {
                return ResourceManager.GetString("设备3优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备3停机时间 {
            get {
                return ResourceManager.GetString("设备3停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3压力 的本地化字符串。
        /// </summary>
        internal static string 设备3压力 {
            get {
                return ResourceManager.GetString("设备3压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备3启用轮换 {
            get {
                return ResourceManager.GetString("设备3启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备3最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备3最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备3运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备3运行时间 {
            get {
                return ResourceManager.GetString("设备3运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4 的本地化字符串。
        /// </summary>
        internal static string 设备4 {
            get {
                return ResourceManager.GetString("设备4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4优先级 的本地化字符串。
        /// </summary>
        internal static string 设备4优先级 {
            get {
                return ResourceManager.GetString("设备4优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备4停机时间 {
            get {
                return ResourceManager.GetString("设备4停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4压力 的本地化字符串。
        /// </summary>
        internal static string 设备4压力 {
            get {
                return ResourceManager.GetString("设备4压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备4启用轮换 {
            get {
                return ResourceManager.GetString("设备4启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备4最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备4最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备4运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备4运行时间 {
            get {
                return ResourceManager.GetString("设备4运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5 的本地化字符串。
        /// </summary>
        internal static string 设备5 {
            get {
                return ResourceManager.GetString("设备5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5优先级 的本地化字符串。
        /// </summary>
        internal static string 设备5优先级 {
            get {
                return ResourceManager.GetString("设备5优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备5停机时间 {
            get {
                return ResourceManager.GetString("设备5停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5压力 的本地化字符串。
        /// </summary>
        internal static string 设备5压力 {
            get {
                return ResourceManager.GetString("设备5压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备5启用轮换 {
            get {
                return ResourceManager.GetString("设备5启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备5最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备5最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备5运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备5运行时间 {
            get {
                return ResourceManager.GetString("设备5运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6 的本地化字符串。
        /// </summary>
        internal static string 设备6 {
            get {
                return ResourceManager.GetString("设备6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6优先级 的本地化字符串。
        /// </summary>
        internal static string 设备6优先级 {
            get {
                return ResourceManager.GetString("设备6优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备6停机时间 {
            get {
                return ResourceManager.GetString("设备6停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6压力 的本地化字符串。
        /// </summary>
        internal static string 设备6压力 {
            get {
                return ResourceManager.GetString("设备6压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备6启用轮换 {
            get {
                return ResourceManager.GetString("设备6启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备6最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备6最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备6运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备6运行时间 {
            get {
                return ResourceManager.GetString("设备6运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7 的本地化字符串。
        /// </summary>
        internal static string 设备7 {
            get {
                return ResourceManager.GetString("设备7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7优先级 的本地化字符串。
        /// </summary>
        internal static string 设备7优先级 {
            get {
                return ResourceManager.GetString("设备7优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备7停机时间 {
            get {
                return ResourceManager.GetString("设备7停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7压力 的本地化字符串。
        /// </summary>
        internal static string 设备7压力 {
            get {
                return ResourceManager.GetString("设备7压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备7启用轮换 {
            get {
                return ResourceManager.GetString("设备7启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备7最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备7最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备7运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备7运行时间 {
            get {
                return ResourceManager.GetString("设备7运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8 的本地化字符串。
        /// </summary>
        internal static string 设备8 {
            get {
                return ResourceManager.GetString("设备8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8优先级 的本地化字符串。
        /// </summary>
        internal static string 设备8优先级 {
            get {
                return ResourceManager.GetString("设备8优先级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8停机时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备8停机时间 {
            get {
                return ResourceManager.GetString("设备8停机时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8压力 的本地化字符串。
        /// </summary>
        internal static string 设备8压力 {
            get {
                return ResourceManager.GetString("设备8压力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8启用轮换 的本地化字符串。
        /// </summary>
        internal static string 设备8启用轮换 {
            get {
                return ResourceManager.GetString("设备8启用轮换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8最大功率 的本地化字符串。
        /// </summary>
        internal static string 设备8最大功率_kw_ {
            get {
                return ResourceManager.GetString("设备8最大功率[kw]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备8运行时间[毫秒] 的本地化字符串。
        /// </summary>
        internal static string 设备8运行时间 {
            get {
                return ResourceManager.GetString("设备8运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备故障 的本地化字符串。
        /// </summary>
        internal static string 设备故障 {
            get {
                return ResourceManager.GetString("设备故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备1是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备1是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备1是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备2是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备2是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备2是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备3是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备3是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备3是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备4是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备4是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备4是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备5是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备5是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备5是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备6是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备6是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备6是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备7是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备7是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备7是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置设备8是否允许轮换调度 的本地化字符串。
        /// </summary>
        internal static string 设置设备8是否允许轮换调度 {
            get {
                return ResourceManager.GetString("设置设备8是否允许轮换调度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度间隔[秒] 的本地化字符串。
        /// </summary>
        internal static string 调度间隔_秒_ {
            get {
                return ResourceManager.GetString("调度间隔[秒]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮换休眠时间[小时] 的本地化字符串。
        /// </summary>
        internal static string 轮换休眠时间_小时_ {
            get {
                return ResourceManager.GetString("轮换休眠时间[小时]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮换时间[小时] 的本地化字符串。
        /// </summary>
        internal static string 轮换时间_小时_ {
            get {
                return ResourceManager.GetString("轮换时间[小时]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软启动故障 的本地化字符串。
        /// </summary>
        internal static string 软启动故障 {
            get {
                return ResourceManager.GetString("软启动故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴承温度高 的本地化字符串。
        /// </summary>
        internal static string 轴承温度高 {
            get {
                return ResourceManager.GetString("轴承温度高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string 运行 {
            get {
                return ResourceManager.GetString("运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行功率倍数 的本地化字符串。
        /// </summary>
        internal static string 运行功率倍数 {
            get {
                return ResourceManager.GetString("运行功率倍数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预警过久停机 的本地化字符串。
        /// </summary>
        internal static string 预警过久停机 {
            get {
                return ResourceManager.GetString("预警过久停机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风机变频器故障 的本地化字符串。
        /// </summary>
        internal static string 风机变频器故障 {
            get {
                return ResourceManager.GetString("风机变频器故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风机变频器故障IO 的本地化字符串。
        /// </summary>
        internal static string 风机变频器故障IO {
            get {
                return ResourceManager.GetString("风机变频器故障IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风机变频器通讯故障 的本地化字符串。
        /// </summary>
        internal static string 风机变频器通讯故障 {
            get {
                return ResourceManager.GetString("风机变频器通讯故障", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风机过载 的本地化字符串。
        /// </summary>
        internal static string 风机过载 {
            get {
                return ResourceManager.GetString("风机过载", resourceCulture);
            }
        }
    }
}
