<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net9.0;netstandard2.1;</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>5.0.4</Version>
	<Description>This is an ORM processing framework，The source address：https://gitee.com/reread_x/openaiot。 This software package is a Sqlite driver for the MyAccess framework，Usage Guide https://www.nuget.org/packages/MyAccess。</Description>
	<PackageReadmeFile>MyAccess 完整使用手册.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageProjectUrl>https://github.com/wrq147/OpenAIot</PackageProjectUrl>
	<LangVersion>10.0</LangVersion>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\MyAccess 完整使用手册.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.8" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyAccess\MyAccess.csproj" />
  </ItemGroup>

</Project>
