<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
    <DocumentationFile>..\..\App\XML\MonitorService.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.13.1" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.13.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AuthService\AuthService.csproj" />
  </ItemGroup>
</Project>
