<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>4.7.4</Version>
    <Description>A modular MVC framework，This is the .net core support component. The source address：https://gitee.com/mz-cn/MZFrame</Description>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateAction\TemplateAction.csproj" />
  </ItemGroup>

</Project>
