<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<AssemblyVersion>8.0.0.1</AssemblyVersion>
		<ProductVersion>8.0.0.1</ProductVersion>
		<Version>8.0.0.1</Version>
		<FileVersion>8.0.0.1</FileVersion>
		<Description>For ZLMediakit api 2025-11-25 commit, git hash:7b2bd22, https://github.com/ZLMediaKit/ZLMediaKit/commit/7b2bd221eac4086358d081f4f0bfeb2a95b050f2.</Description>
	</PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Libs\**" />
    <EmbeddedResource Remove="Libs\**" />
    <None Remove="Libs\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ZLMediaLibs\Windows\x64\ext-codec.lib" />
    <None Remove="ZLMediaLibs\Windows\x64\zlmediakit.lib" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ZLMediaLibs\Linux\x64\libmk_api.so">
		<Link>libmk_api.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\avcodec-59.dll">
		<Link>avcodec-59.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\avdevice-59.dll">
		<Link>avdevice-59.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\avfilter-8.dll">
		<Link>avfilter-8.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\avformat-59.dll">
		<Link>avformat-59.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\avutil-57.dll">
		<Link>avutil-57.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\libcrypto-3-x64.dll">
		<Link>libcrypto-3-x64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\libssl-3-x64.dll">
		<Link>libssl-3-x64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\mk_api.dll">
		<Link>mk_api.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\postproc-56.dll">
		<Link>postproc-56.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\srtp2.dll">
		<Link>srtp2.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\swresample-4.dll">
		<Link>swresample-4.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\swscale-6.dll">
		<Link>swscale-6.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZLMediaLibs\Windows\x64\x264.dll">
		<Link>x264.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ZLMediaLibs\Linux\arm\" />
  </ItemGroup>
</Project>
