<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>GB28181SipGate</RootNamespace>
        <Nullable>disable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Management" Version="7.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SipSorcery\SIPSorcery.csproj" />
    </ItemGroup>

</Project>
