<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.31" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.31" />
		<PackageReference Include="Minio" Version="5.0.2" />
		<PackageReference Include="Onvif.Core" Version="3.0.0" />
		<PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChannelUtility\ChannelUtility.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="config.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
